---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: customize-test
  name: customize-test
  namespace: customize-demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customize-test
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: customize-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
