apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customize-test
  name: customize-test
  namespace: customize-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: customize-test
  type: LoadBalancer
status:
  loadBalancer: {}
